version: "2"
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    container_name: coding-challenge-database
    environment:
      POSTGRES_USER: developer
      POSTGRES_DB: interview
      POSTGRES_PASSWORD: borderpass
